services:
    backend:
        build:
            context: .
            target: development
        ports:
            - '4000:4000'
        volumes:
            - ./src:/app/src
            - ./.env.development:/app/.env.development
            - /app/node_modules
        environment:
            - DATABASE_URL=postgresql://sid:1122@postgres:5432/realtime_notes?schema=public
            - NODE_ENV=development
        depends_on:
            - postgres
        command: npm run dev
        # command: sh -c "npx prisma migrate dev && npm run dev" # Uncomment to auto-migrate on start

    postgres:
        image: postgres:15-alpine
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_USER=sid
            - POSTGRES_PASSWORD=1122
            - POSTGRES_DB=realtime_notes
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
